package service

enum class ConnectionState {
    DISCONNECTED,
    CONNECTED,
    HOST_WAITING_FOR_CONFIRMATION,
    GUEST_WAITING_FOR_CONFIRMATION,
    WAITING_FOR_GUEST,
    WAITING_FOR_INIT,
    PLAYING_MY_TURN,
    WAITING_FOR_OPPONENTS_TURN
}